### ISSUE TITLE
Unitialised string offset error

### ISSUE THREAD

**Issue by Tallboy22** [comes/ecowitt2weewx#2]
Hi - on running, I get the following error text:
  
```
ErrorException

  Uninitialized string offset: 0

  at app/Commands/EcowittExportCommand.php:172
    168▕     protected function getData($stack, $key)
    169▕     {
    170▕         return collect(data_get($stack, $key))
    171▕             ->mapWithKeys(function ($value) {
  ➜ 172▕                 return [$value[0] => $value[1] ?: null];
    173▕             });
    174▕     }
    175▕
    176▕     /**

  1   app/Commands/EcowittExportCommand.php:172
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Uninitialized string offset: 0", "/home/pi/ecowitt2weewx/app/Commands/EcowittExportCommand.php", [""])

      +1 vendor frames
  3   app/Commands/EcowittExportCommand.php:173
      Illuminate\Support\Collection::mapWithKeys(Object(Closure))
```

Grateful for your help to resolve.  I'll be the first to admit, I'm a bit out of my depth with PHP

**Comment by comes** [comment]
Hej @Tallboy22,

thanks for reporting this issue. I think ecowitt changes their data structure. I tried to fix them based on my own data. please update your source and let me know if the problem is solved.

greetings, J

**Comment by Tallboy22** [comment]
Thanks - that's sorted it perfectly !  One final question - I've got some additional temperature/pressure sensors in my EcoWitt set-up.  Where/how do I need to tweak the code to pull these in?

**Comment by comes** [comment]
Hej @Tallboy22,

have a look at https://github.com/comes/ecowitt2weewx/blob/bda227a1a6ec7675af2ffa003164a136405f4fab/app/Commands/EcowittExportCommand.php#L92 the variable ```$ecowitt``` contains all your data.

In line https://github.com/comes/ecowitt2weewx/blob/bda227a1a6ec7675af2ffa003164a136405f4fab/app/Commands/EcowittExportCommand.php#L157 I build the export array. Nice and dirty.

You can extend this array with your own data. Feel free to make a PR for your changes so others can participate too.

greetings, J

**Comment by Tallboy22** [comment]
Thanks - really appreciated.  Sorry - forgive my ignorance - how do I interogate $ecowitt at run-time to understand how it's storing the additional sensors?   Have you ever found any documentation for the EcoWitt API?

**Comment by comes** [comment]
Hej, no I never found some official documentation. Everything is based on my own reverse engineering.

To dump the Ecowitt variable, you can use dump() or dd()

`dd($ecowitt);` is your friend.

**Comment by comes** [comment]
close issue; no response
