### ISSUE TITLE
Error on running export command

### ISSUE THREAD

**Issue by Tallboy22** [comes/ecowitt2weewx#3]
Hi - I'm not very experienced in building with Laravel, but I'm getting an error when running "php ecowitt2weewx app:build" as follows:

" ErrorException
  rename(/home/ecowitt2weewx/ecowitt2weewx.phar,/home/ecowitt2weewx/builds/ecowitt2weewx): No such file or directory"

Grateful for any help you could offer

**Comment by comes** [comment]
Hej @Tallboy22,

thank you for reporting, I've solved this issue.
