### ISSUE TITLE
Dependency non existent

### ISSUE THREAD

**Issue by notnullxyz** [comes/ecowitt2weewx#7]
Hi
I am not entirely sure, but this seems like a deprecated dep being used.
If you know what to pull in with composer, I will test and submit a PR or is there's something else I am missing?
Stuck here, myself.

Output of execution:

**@goatbox:~/TMP_ECOWITT_TO_WEEWX/ecowitt2weewx-main# ./ecowitt2weewx export --user ****@protonmail.com --pass mycatsmaidenname 2022-01-01 2023-10-29

  ```
 Illuminate\Contracts\Container\BindingResolutionException

  Target class [Illuminate\Http\Client\Factory] does not exist.

  at vendor/illuminate/container/Container.php:916
    912▕
    913▕         try {
    914▕             $reflector = new ReflectionClass($concrete);
    915▕         } catch (ReflectionException $e) {
  ➜ 916▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    917▕         }
    918▕
    919▕         // If the type is not instantiable, the developer is attempting to resolve
    920▕         // an abstract type such as an Interface or Abstract Class and there is

      +10 vendor frames

  11  app/Commands/EcowittExportCommand.php:212
      Illuminate\Support\Facades\Facade::__callStatic()

  12  app/Commands/EcowittExportCommand.php:62
      App\Commands\EcowittExportCommand::getSessionId()

```

**Comment by notnullxyz** [comment]
Doing a manual installation of the following, solves the problem:
` php ecowitt2weewx app:install http`

**Comment by comes** [comment]
Interesting. I need to check this later today. the HTTP Facade is used by the framework itself.
